# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: The default task
    cmds:
      - echo "hey!"
    silent: true
    
  build:
    desc: Builds the Daemon and the CLI
    cmds:
      - go build ./cmd/veloq
      - go build ./cmd/veloqd
